name: eInk-weather-display

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
          cache-dependency-path: "requirements/development.txt"
      - name: Update pip
        run: pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r requirements/development.txt
      - name: Check the code compiles
        run: python -m compileall -q .
      - name: Lint with flake8
        run: flake8
      - name: Run tests
        run: python -m unittest discover -s eInk-weather-display
